### ISSUE TITLE
Errors when running on Manjaro arch

### ISSUE THREAD

**Issue by luandro** [sedwards2009/llm-multitool#1]
```
2024/01/20 06:33:06 Error occurred while scanning storage: open data: no such file or directory
panic: Error occurred while scanning storage: open data: no such file or directory

goroutine 1 [running]:
log.Panicf({0x8f3c15?, 0x40e8e5?}, {0xc00031fe40?, 0x30?, 0x28?})
	/opt/hostedtoolcache/go/1.21.1/x64/src/log/log.go:439 +0x65
sedwards2009/llm-multitool/internal/mem_storage.(*SimpleStorage).scan(0xc000471020)
	/home/runner/work/llm-multitool/llm-multitool/backend/internal/mem_storage/mem_storage.go:45 +0x74
sedwards2009/llm-multitool/internal/mem_storage.New({0x8d47d9, 0x4})
	/home/runner/work/llm-multitool/llm-multitool/backend/internal/mem_storage/mem_storage.go:37 +0xad
main.setupStorage(...)
	/home/runner/work/llm-multitool/llm-multitool/backend/main.go:39
main.main()
	/home/runner/work/llm-multitool/llm-multitool/backend/main.go:673 +0x3e
```

**Comment by sedwards2009** [comment]
Create a `data` directory for it to use first. It won't make one automatically.
